# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  "0 8 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

    # Runs a set of commands using the runners shell
    - name: Update
      run: |
        rm -f host adblocker dnsmasq.conf smartdns.conf domain clash
        wget --no-check-certificate -t 1 -T 10 https://raw.githubusercontent.com/neodevpro/neodevhost/master/host
        wget --no-check-certificate -t 1 -T 10 https://raw.githubusercontent.com/neodevpro/neodevhost/master/adblocker
        wget --no-check-certificate -t 1 -T 10 https://raw.githubusercontent.com/neodevpro/neodevhost/master/dnsmasq.conf
        wget --no-check-certificate -t 1 -T 10 https://raw.githubusercontent.com/neodevpro/neodevhost/master/smartdns.conf
        wget --no-check-certificate -t 1 -T 10 https://raw.githubusercontent.com/neodevpro/neodevhost/master/domain
        wget --no-check-certificate -t 1 -T 10 https://raw.githubusercontent.com/neodevpro/neodevhost/master/clash
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5.1.0
      with:
           commit_message: Auto Update
           branch: master
           commit_options: '--no-verify --signoff'
           repository: .
           commit_user_name: FusionPlmH
           commit_user_email: leemenhin@gmail.com
           push_options: '--force'
